.gitignore, Gemfile, Gemfile.lock, README.md, package.json, src/resources/.zat, webpack.config.js
https://issues.liferay.com/browse/LRIS-31343
=> LRIS-31343 Incorporate Zendesk app tools in Zendesk theme

src/css/_zendesk-header.scss, src/css/main.scss, src/resources/templates/header.hbs
Hey @rdai10,
Attached is an update for http://issues.liferay.com/browse/LRIS-31358.
The header is limited in what it can access.  I am not sure if there is a way to custom the drop down menu as described in http://issues.liferay.com/browse/LRIS-31358.  As for the search bar, there is going to be JS that is needed to get it to slide in and out, but that would mean we would also have to customize the widget again.
=> LRIS-31358

src/css/_zendesk-pagination.scss, src/css/_zendesk-search.scss, src/css/_zendesk-variables.scss, src/css/main.scss, src/resources/templates/search_results.hbs
Hey @rdai10,
Attached is an update for http://issues.liferay.com/browse/LRIS-31532.
There is a limitation with the meta data we can display a the bottom of the search result list, so I just used the default one for now.  Also, we still need to style the no results message, but there wasn't a mockup for that so I just left it as is for now.
=> LRIS-31532

src/css/_zendesk-pagination.scss
Hey @rdai10,
Attached is an update for http://issues.liferay.com/browse/LRIS-31617.
=> LRIS-31617

src/css/_zendesk-elements.scss, src/css/_zendesk-header.scss, src/css/_zendesk-variables.scss, src/resources/templates/article_page.hbs, src/resources/templates/category_page.hbs, src/resources/templates/community_post_list_page.hbs, src/resources/templates/community_post_page.hbs, src/resources/templates/community_topic_list_page.hbs, src/resources/templates/community_topic_page.hbs, src/resources/templates/contributions_page.hbs, src/resources/templates/footer.hbs, src/resources/templates/header.hbs, src/resources/templates/home_page.hbs, src/resources/templates/new_community_post_page.hbs, src/resources/templates/new_request_page.hbs, src/resources/templates/request_page.hbs, src/resources/templates/requests_page.hbs, src/resources/templates/search_results.hbs, src/resources/templates/section_page.hbs
Hey @rdai10,
Attached is an update for http://issues.liferay.com/browse/LRIS-31749.
=> LRIS-31749

src/css/_zendesk-header.scss, src/css/_zendesk-requests.scss, src/css/_zendesk-search.scss
Hey @rdai10,
Attached is an update for http://issues.liferay.com/browse/LRIS-31912.
=> LRIS-31912

src/css/_zendesk-article.scss, src/css/_zendesk-breadcrumb.scss, src/css/_zendesk-category-section.scss, src/css/_zendesk-elements.scss, src/css/_zendesk-error.scss, src/css/_zendesk-footer.scss, src/css/_zendesk-homepage.scss, src/css/_zendesk-notification.scss, src/css/_zendesk-requests.scss, src/css/_zendesk-search.scss, src/css/_zendesk-variables.scss, src/resources/templates/request_page.hbs
Hey @rdai10,
Attached is an update for http://issues.liferay.com/browse/LRIS-31906.
=> LRIS-31906

theme/src/resources/templates/category_pages/documentation.hbs, theme/src/resources/templates/document_head.hbs
https://issues.liferay.com/browse/LRIS-33049?focusedCommentId=1552903&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1552903
cc @jonmak08
=> LRIS-33049

theme/src/css/_zendesk-cards.scss, theme/src/css/_zendesk-category-section.scss, theme/src/resources/templates/document_head.hbs
https://issues.liferay.com/browse/LRIS-32879
cc @jonmak08
=> LRIS-32879 designer feedback

theme/src/resources/templates/article_page.hbs, theme/src/resources/templates/article_pages/zendesk_default.hbs, theme/src/resources/templates/category_pages/liferay_analytics_cloud.hbs, theme/src/resources/templates/category_pages/liferay_commerce.hbs, theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
https://issues.liferay.com/browse/LRIS-32572?focusedCommentId=1556060&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1556060
cc @jonmak08
=> LRIS-32572 rename official docs article template as default for ease of import

theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-requests.scss, theme/src/js/helpers/api-helpers.js, theme/src/js/helpers/user-permissions.js, theme/src/js/index.js, theme/src/resources/templates/request_page.hbs
https://issues.liferay.com/browse/LRIS-32774
for testing: 
https://issues.liferay.com/browse/LRIS-32774?focusedCommentId=1561188&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1561188
cc: @jonmak08
=> LRIS-32774

theme/src/js/helpers/user-permissions.js
=> LRIS-32774 typo

theme/src/resources/templates/document_head.hbs
https://issues.liferay.com/browse/LRIS-33664
=> LRIS-33664 Restrict Google from Indexing Zendesk

theme/src/js/vendor/zendesk-watcher-customization.js
https://issues.liferay.com/browse/LRIS-34012
=> LRIS-34012 Fix bug where watcher org is selected when creating a ticket

theme/src/js/components/DocSideNav.js, theme/src/js/helpers/api-helpers.js, theme/src/js/index.js
cc @jonmak08 While working on LRIS-31533, I cleaned up the api helpers (combined helper functions and removed unnecessary export). I also added js docs for easier readability. 
LRIS-31533 itself went through requirement changes as I surfaced questions and is back in analysis for stakeholder to clarify scope. Since I made code improvements, I'm commiting the changes against that ticket number. The actual ticket doesn't need to be workflowed.
=> LRIS-31533 add js doc and clean up api helpers

theme/src/css/_zendesk-requests.scss, theme/src/css/_zendesk-variables.scss
I think reverting font size changes is enough right? Let me know if I missed anything else. Thanks.
=> LRIS-34351 - Revert variable changes for font-size

theme/src/js/components/Pagination.js, theme/src/js/components/SearchResults.js
Hey @rdai10,
Attached is an update for http://issues.liferay.com/browse/LRIS-34673.
=> LRIS-34673

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Update Latest Release link on Commerce Page

theme/src/resources/templates/new_request_page.hbs
https://issues.liferay.com/browse/LHC-269
=> LHC-269 Renamed commerce component

theme/src/resources/templates/category_pages/liferay_dxp_7_0.hbs
=> Update Service Packs Archive Link

theme/src/resources/templates/category_pages/liferay_dxp_7_1.hbs
=> Updated 4 links

theme/src/resources/templates/category_pages/liferay_dxp_7_0.hbs
=> Updated Patching Tool download link

theme/src/resources/templates/category_pages/liferay_portal_6_2.hbs
=> Updated six download links

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Updated Latest Release link

theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-variables.scss
https://issues.liferay.com/browse/LHC-65
cc: @jonmak08
=> LHC-65 keeping the variables and styling consistent across Zendesk and Customer Liferay

theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-variables.scss
Adjust label spacing per designer suggestion.
=> LHC-482 tweak label-sm spacing

theme/src/resources/templates/category_pages/liferay_commerce.hbs
https://issues.liferay.com/browse/LHC-557
=> LHC-557 Update commerce latest link

theme/src/css/_zendesk-article.scss, theme/src/css/_zendesk-breadcrumb.scss, theme/src/css/_zendesk-call-to-action.scss, theme/src/css/_zendesk-category-section.scss, theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-requests.scss, theme/src/css/_zendesk-search.scss, theme/src/css/_zendesk-variables.scss, theme/src/js/components/CallToAction.js, theme/src/js/components/DocSideNav.js, theme/src/js/components/SearchFilter.js, theme/src/js/components/SearchResults.js, theme/src/js/components/__tests__/__snapshots__/CallToAction.js.snap, theme/src/js/components/__tests__/__snapshots__/DocSideNav.js.snap, theme/src/js/components/__tests__/__snapshots__/SearchFilter.js.snap, theme/src/js/components/__tests__/__snapshots__/SearchResults.js.snap, theme/src/js/vendor/zendesk-watcher-customization.js, theme/src/resources/templates/article_page.hbs, theme/src/resources/templates/article_pages/zendesk_default.hbs, theme/src/resources/templates/category_page.hbs, theme/src/resources/templates/category_pages/liferay_commerce.hbs, theme/src/resources/templates/footer.hbs, theme/src/resources/templates/home_page.hbs, theme/src/resources/templates/request_page.hbs, theme/src/resources/templates/search_results.hbs, theme/src/resources/templates/section_page.hbs
Merge all changes for the biweekly sprint. There will be no release this friday (4/26/19) since Cole is out. The next release will still be two weeks from tomorrow on May 10.
=> merge changes from current sprint end on 4/26/19

theme/src/resources/templates/category_pages/liferay_dxp_7_1.hbs
=> Updated "Latest Release" Links

theme/src/resources/templates/category_pages/liferay_dxp_7_0.hbs
=> Updated 2 Latest Release Links

theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs
https://issues.liferay.com/browse/LHC-397
=> LHC-397 restructure kb article template and fast track template for better white space balance

theme/src/resources/templates/article_pages/general_article.hbs
https://issues.liferay.com/browse/LHC-397?focusedCommentId=1820980&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1820980
=> LHC-397 update general article too for better white space balance

theme/src/resources/templates/category_pages/documentation.hbs
=> Updated DXP Cloud Documentation link

theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
=> Updated Documentation Link

theme/src/css/_zendesk-article.scss, theme/src/resources/templates/article_page.hbs, theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/general_article.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs, theme/src/resources/templates/article_pages/zendesk_default.hbs
=> LHC-397 consistent spacing around headings in articles

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Updated "latest release" link

theme/src/resources/templates/search_results.hbs
Add 7.2 to search results product filter
https://issues.liferay.com/browse/LHC-774
For this to properly work, we will need 
[ ] The official docs import to be complete. https://issues.liferay.com/browse/LHC-579.
[ ] Make sure all 7.2 docs have the `DXP 7.2` label.
[ ] @cole-liferay to add the `mega_menu-dxp_7_2` dynamic content.
=> LHC-774 add 7.2 to search results product filter

theme/package-lock.json, theme/src/resources/templates/new_request_page.hbs
https://issues.liferay.com/browse/LHC-775
In order for this to fully work, pending on:
[ ] The official docs import to be complete. https://issues.liferay.com/browse/LHC-579.
[ ] Shalaka to add the 7.2 product configuration to Help Center.
=> LHC-775 allow custom article suggestion to make query against 7.2 docs

theme/package-lock.json
=> Revert "Bump tar from 2.2.1 to 2.2.2 in /theme"

theme/package-lock.json, theme/package.json
=> Revert "Bump eslint-plugin-prettier from 2.6.0 to 2.7.0 in /theme"

theme/src/css/_zendesk-article.scss, theme/src/resources/templates/article_page.hbs, theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/general_article.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs, theme/src/resources/templates/article_pages/zendesk_default.hbs
https://issues.liferay.com/browse/LHC-746
@jonmak08
=> LHC-746 article feedback redesign

theme/src/css/_zendesk-breadcrumb.scss, theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-search.scss, theme/src/css/_zendesk-variables.scss, theme/src/js/components/SearchFilter.js, theme/src/js/components/__tests__/__snapshots__/SearchFilter.js.snap, theme/src/js/components/__tests__/__snapshots__/SearchResults.js.snap
https://issues.liferay.com/browse/LHC-743
=> LHC-743 search page redesign

theme/src/resources/templates/header.hbs
auto update locale when navigate to customer help center
=> LHC-675 auto update locale when navigate to customer help center

theme/src/resources/templates/header.hbs, theme/src/resources/templates/home_page.hbs
update dynamic content on homepage
=> LHC-835 update dynamic content on homepage

theme/src/resources/templates/category_pages/documentation.hbs, theme/src/resources/templates/category_pages/liferay_commerce.hbs, theme/src/resources/templates/category_pages/liferay_dxp_7_0.hbs, theme/src/resources/templates/category_pages/liferay_dxp_7_1.hbs, theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs, theme/src/resources/templates/category_pages/liferay_portal_6_1.hbs, theme/src/resources/templates/category_pages/liferay_portal_6_2.hbs
Update content for 7.2 release. 
We're still missing the download links. We won't be able to get them until Nicole updates it on her end. Once we have the links, will update the theme again.
=> LHC-616 Update content for 7.2 release

theme/src/resources/templates/category_pages/documentation.hbs
=> Updated 7.1 Dev Reference Link

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Updated download links

theme/src/css/_zendesk-cards.scss, theme/src/css/_zendesk-homepage.scss, theme/src/resources/templates/home_page.hbs
Make the CTA section on homepage look better
=> LHC-733 update cta section to make it look good on all breakpoints

README.md, theme/package-lock.json, theme/package.json, theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-header.scss, theme/src/css/_zendesk-search.scss, theme/src/css/_zendesk-variables.scss, theme/src/js/components/__tests__/__snapshots__/CallToAction.js.snap, theme/src/js/components/__tests__/__snapshots__/ProductTabs.js.snap, theme/src/resources/templates/article_page.hbs, theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/general_article.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs, theme/src/resources/templates/article_pages/zendesk_default.hbs, theme/src/resources/templates/header.hbs
https://issues.liferay.com/browse/LHC-125
=> LHC-125 update mega menu to be click activated and apply redesign styling

theme/src/css/_zendesk-footer.scss, theme/src/resources/templates/footer.hbs
https://issues.liferay.com/browse/LHC-740
=> LHC-740 redesign footer

theme/src/css/_zendesk-footer.scss, theme/src/css/_zendesk-header.scss, theme/src/resources/templates/footer.hbs
https://issues.liferay.com/browse/LHC-867
=> LHC-867 change the color of navbar links

theme/src/css/_zendesk-cards.scss, theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-requests.scss, theme/src/css/_zendesk-search.scss, theme/src/css/_zendesk-variables.scss
https://issues.liferay.com/browse/LHC-742
=> LHC-742 update all inputs

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Updated Compatibility Matrix Link

theme/package-lock.json, theme/package.json, theme/src/css/_zendesk-header.scss, theme/src/resources/templates/header.hbs
https://issues.liferay.com/browse/LHC-852
=> LHC-852 Click on current active menu item to close menu

theme/src/resources/templates/search_results.hbs
https://issues.liferay.com/browse/LHC-908
=> LHC-908 encode URI component

theme/Gemfile.lock, theme/src/resources/templates/search_results.hbs
https://issues.liferay.com/browse/LHC-883
=> LHC-883 Update search results filter to look for "Commerce" label instead of "Commerce 1.0"

theme/src/css/_zendesk-elements.scss, theme/src/js/components/SearchResults.js
https://issues.liferay.com/browse/LHC-891
=> LHC-891 nicer looking fast track label

theme/src/css/_zendesk-article.scss, theme/src/css/_zendesk-variables.scss, theme/src/js/components/DocTOC.js, theme/src/js/index.js, theme/src/resources/templates/article_page.hbs, theme/webpack.common.js
https://issues.liferay.com/browse/LHC-183
=> LHC-183 table of contents sidebar

theme/src/js/index.js, theme/src/resources/templates/category_pages/developer_services.hbs, theme/src/resources/templates/home_page.hbs, theme/webpack.prod.js
https://issues.liferay.com/browse/LHC-903
=> LHC-903 Add developer services product on Zendesk

theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
=> Added Product Support Card

theme/src/css/_zendesk-article.scss, theme/src/css/_zendesk-cards.scss
https://issues.liferay.com/browse/LHC-187
=> LHC-187 Redesign last styling tweaks

theme/src/js/components/DocTOC.js, theme/src/resources/templates/article_page.hbs
https://issues.liferay.com/browse/LHC-183
=> LHC-183 account for inconsistent official docs markups

theme/src/resources/templates/category_pages/developer_services.hbs
https://issues.liferay.com/browse/LHC-903
=> LHC-903 update developer services content

theme/src/css/_zendesk-variables.scss
https://issues.liferay.com/browse/LHC-729
=> LHC-729 update brand color

theme/documentation/permissions.md, theme/src/resources/templates/home_page.hbs
Based on [this request](https://issues.liferay.com/browse/LHC-733?focusedCommentId=1897734&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1897734), only signed in users with KB tags will be able to see the quick links.
=> LHC-733 permission quick links to only signed in users with KB tag

theme/src/resources/templates/footer.hbs
https://issues.liferay.com/browse/LHC-232
=> LHC-232 add aria label to links with no discernible text

theme/documentation/permissions.md
Update documentation for Developer Services product. Including steps for admin to ensure that the interaction works properly.
cc: @cole-liferay
=> LHC-733 clarify developer services and add necessary steps to enable

theme/src/resources/templates/category_pages/liferay_dxp_7_1.hbs
=> Updated Documentation Links

theme/src/css/_zendesk-article.scss, theme/src/css/_zendesk-header.scss, theme/src/resources/templates/article_page.hbs, theme/src/resources/templates/article_pages/zendesk_default.hbs, theme/src/resources/templates/header.hbs
https://issues.liferay.com/browse/LHC-201
=> LHC-201 collapsible sidebar for official docs on mobile

theme/documentation/article_pages.md
While doing discovery for the various ways to add article feedback, I noticed that the documentation could be improved. https://issues.liferay.com/browse/LHC-193
=> LHC-193 update article pages docs to mention toc

theme/src/js/helpers/article-suggestion.js
When a user clicks on the article suggestion when they are in the process of creating a ticket, it's easier for them if the suggestions open as new tabs so they don't have to go back to the ticket form to see other suggestions or fill out the form fields again. 
https://issues.liferay.com/browse/LHC-487
=> LHC-487 when user clicks on create ticket form article suggestion, open in new tab

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Fix Pack Card Updates

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Added Whitepapers Card

theme/src/resources/templates/category_pages/documentation.hbs
=> Added 7.2 Whitepapers Link

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Added Integrated Technologies card

theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
=> Updated Getting Started link

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Removed JA Banner

theme/src/resources/templates/category_pages/developer_services.hbs
=> Updated Documentation Card Heading

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Added Upgrading Cards

theme/src/resources/templates/category_pages/developer_services.hbs
Somehow, the links were reverted in this last release.
=> Added section links for each card

theme/package.json, theme/src/css/_zendesk-category-section.scss, theme/src/css/_zendesk-elements.scss, theme/src/css/_zendesk-homepage.scss, theme/src/css/_zendesk-notification.scss, theme/src/css/_zendesk-requests.scss, theme/src/css/clay_button_placeholder.scss, theme/src/css/main.scss, theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
Upgraded to latest Clay css. Added banner on the bottom of dxp cloud product page.
=> LHC-1304 DXP Cloud product page banner

theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
Adjust width of banner per stakeholder request
=> LHC-1304 make dxp cloud banner the same width as rest of the content

theme/src/css/_zendesk-elements.scss, theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
Update cta to make it less prominent so it doesn't compete with the cards.
=> LHC-1304 smaller cta on landing page to not compete with cards

theme/src/js/helpers/article-suggestion.js, theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/general_article.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs, theme/src/resources/templates/request_page.hbs
https://issues.liferay.com/browse/LHC-1604
=> LHC-1604 add rel="noopener noreferrer" to links that open in new tabs

theme/src/resources/templates/category_pages/documentation.hbs
Directing to learn.liferay docs
=> Updated Commerce links

theme/src/resources/templates/search_results.hbs
=> Removed Commerce in the search filter

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Updated Commerce links to learn.liferay

theme/src/resources/templates/category_pages/liferay_dxp_7_1.hbs
=> Updated SP and FP Links

theme/documentation/article_pages.md, theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs
=> LHC-1565 Remove "Related Articles" feature from article templates

theme/src/resources/templates/category_pages/developer_services.hbs
=> Added FAQ Card and Description

theme/src/resources/templates/category_pages/liferay_dxp_7_0.hbs
=> LHC-1669 break dynamic content into 2

theme/package-lock.json, theme/package.json, theme/src/js/script.js, theme/src/resources/templates/document_head.hbs, theme/webpack.common.js, theme/webpack.prod.js
https://issues.liferay.com/browse/LHC-1718
=> LHC-1718 use cdn for script file to circumvent file size limitation

theme/package-lock.json, theme/src/css/_zendesk-search.scss, theme/src/js/components/SearchInput.js, theme/src/js/components/SearchResults.js, theme/src/js/components/__tests__/__snapshots__/SearchResults.js.snap, theme/src/resources/templates/search_results.hbs
https://issues.liferay.com/browse/LHC-1722
=> LHC-1722 Create search input on search page to set query term on swiftype driver

theme/src/resources/templates/category_pages/liferay_commerce.hbs
- Replaced "Admin Guide" with "Documentation"
- Updated icon to "getting-started svg
=> Updated Admin Guide Card

theme/src/resources/templates/category_pages/documentation.hbs
- Replaced "Admin Guide' with "Documentation"
=> Updated Commerce Admin Guide description

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Added "Help Topics" card

theme/src/resources/templates/category_pages/liferay_analytics_cloud.hbs
=> Removed Feature Requests and Known Issues Cards

theme/src/resources/templates/new_request_page.hbs
https://issues.liferay.com/browse/LHC-1694
=> LHC-1694 add cross-cluster replication component

theme/src/resources/templates/new_request_page.hbs
https://issues.liferay.com/browse/LHC-1790
=> LHC-1790 update create ticket product filter logic per zendesk backend changes

theme/src/resources/templates/new_request_page.hbs
https://issues.liferay.com/browse/LHC-1834
=> LHC-1834 change string prototype method to one where ie11 can understand

theme/webpack.prod.js
https://issues.liferay.com/browse/LHC-1824
=> LHC-1824 open help center prod for indexing

theme/src/resources/templates/search_results.hbs
https://issues.liferay.com/browse/LHC-1636
=> LHC-1636 remove DXP Cloud product filter from Search

theme/src/css/_zendesk-article.scss
https://issues.liferay.com/browse/LHC-1115
=> LHC-1115 remove extra space at beginning of code snippet

theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
=> Removed Knowledge Base card

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Updated Support Coverage Link

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Add Japanese banner with link to Commerce docs

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Updated link URL in banner

theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs
https://issues.liferay.com/browse/LHC-2189
=> LHC-2189 article attachments should not be visible to users who have been gated

theme/src/js/helpers/gated-content.js, theme/src/js/index.js, theme/src/resources/templates/article_pages/fast_track.hbs, theme/src/resources/templates/article_pages/knowledge_base.hbs, theme/src/resources/templates/article_pages/zendesk_default.hbs
https://issues.liferay.com/browse/LHC-2225
=> LHC-2225 gate zendesk default template

theme/src/resources/templates/category_pages/liferay_commerce.hbs
=> Updated info banner link

theme/src/css/_zendesk-notification.scss, theme/src/resources/templates/header.hbs
https://issues.liferay.com/browse/LHC-2326
A temporary security banner on the top of Help Center. When dismissed it will no longer show up until user closes the current session.
=> LHC-2326 security banner

theme/src/css/_zendesk-notification.scss, theme/src/resources/templates/header.hbs
https://issues.liferay.com/browse/LHC-2340
=> LHC-2340 remove site wide notifcation on May 8th

theme/src/resources/templates/category_pages/liferay_dxp_7_1.hbs
=> Updated Latest Release links

theme/src/resources/templates/category_pages/developer_services.hbs
=> Updated Card Links

theme/src/resources/templates/category_pages/liferay_dxp_7_0.hbs
Discussion ongoing about EOL for 7.0
=> Removed alert banner

theme/src/css/_zendesk-notification.scss, theme/src/resources/templates/header.hbs
https://issues.liferay.com/browse/LHC-2468
=> LHC-2381, LHC-2368 new banner notification

theme/src/resources/templates/header.hbs
Article links currently all go to LSV-412.
=> LHC-2381 Fix article links

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
Top Resources - Security Advisories
Downloads - Service Packs
Downloads - Security
=> Added 3 cards

theme/src/resources/templates/category_pages/documentation.hbs
=> Updated learn.liferay links

theme/documentation/permissions.md, theme/src/css/_zendesk-requests.scss
https://issues.liferay.com/browse/LHC-2708?focusedCommentId=2204473&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2204473
=> LHC-2708 able to accurately refect required fields on ticket form now

theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
=> Updated the Documentation link

.github/workflows/sandbox-deploy.yml, theme/src/resources/templates/new_request_page.hbs
https://issues.liferay.com/browse/LHC-2785
=> LHC-2785 Add new 7.3 configurations on the ticket form

theme/src/css/_zendesk-requests.scss
https://issues.liferay.com/browse/LHC-2815
=> LHC-2815 make ticket form small text consistent color

theme/README.md, theme/src/resources/templates/header.hbs, theme/src/resources/templates/home_page.hbs, theme/webpack.prod.js
https://issues.liferay.com/browse/ISSUP-2789
=> LHC-2789 Update mega menu for 7.3 release

theme/src/resources/templates/category_pages/liferay_analytics_cloud.hbs
=> Added Announcements card

theme/package-lock.json, theme/src/resources/templates/new_request_page.hbs, theme/src/resources/templates/search_results.hbs
https://issues.liferay.com/browse/ISSUP-2918 & https://issues.liferay.com/browse/ISSUP-2871
=> ISSUP-2918 & ISSUP-2871 add back search filters per request and fully clear product selection when an organization changes on ticket form

theme/src/resources/templates/category_pages/documentation.hbs
=> Added 7.3 section

theme/src/resources/templates/category_pages/liferay_dxp_7_3.hbs
After our initial release on 10/12 at 4pm, I will need to manually update the download link and send you an updated PR. Let me know if you have any questions.
=> Updated template with new production links

theme/src/resources/templates/home_page.hbs
Hi Rebecca, 
Did I already send you a PR for this update? I thought I did, but maybe it was just in my head since I don't see it in the latest theme on sandbox.
=> Updated 6.1 card to article link?

theme/README.md
Include steps for allowing content updaters to upload themes on the zendesk interface themselves.
=> ISSUP-2936 document how to generate theme to be imported on zendesk

theme/src/resources/templates/home_page.hbs
=> Updated Portal 6.1 card link

theme/src/resources/templates/category_pages/liferay_dxp_7_3.hbs
=> Added "Service Life" card

theme/src/css/_zendesk-notification.scss, theme/src/resources/templates/header.hbs
https://issues.liferay.com/browse/ISSUP-3338
=> ISSUP-3338 temp banner

theme/src/resources/templates/category_pages/liferay_dxp_7_3.hbs
=> Created new tabs and cards

theme/src/resources/templates/category_pages/liferay_dxp_7_3.hbs
=> Added Fix Packs and Security Advisories cards

theme/src/resources/templates/category_pages/liferay_analytics_cloud.hbs
=> Updated Link

theme/src/resources/templates/category_pages/liferay_analytics_cloud.hbs
=> Added JP banner

theme/src/resources/templates/home_page.hbs
=> Updated Subscribe link

theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
Per Zeno's request, removed banner until we can create a new landing page on Pardot.
=> Temporarily removed Banner

theme/src/resources/templates/category_pages/liferay_portal_6_2.hbs
=> Removed info banner

knowledge-capture-app/package.json, knowledge-capture-app/spec/NoResults.spec.js, knowledge-capture-app/spec/SearchFilter.spec.js, knowledge-capture-app/spec/SearchResults.spec.js, knowledge-capture-app/spec/app.spec.js, knowledge-capture-app/spec/mocks/mock.js, knowledge-capture-app/src/javascript/lib/utility.js, knowledge-capture-app/src/javascript/modules/Main.js, knowledge-capture-app/src/javascript/modules/NoResults.js, knowledge-capture-app/src/javascript/modules/ResultsBreadcrumb.js, knowledge-capture-app/src/javascript/modules/SearchFilters.js, knowledge-capture-app/src/javascript/modules/SearchInput.js, knowledge-capture-app/src/javascript/modules/SearchResults.js, knowledge-capture-app/src/javascript/modules/app.js, knowledge-capture-app/src/translations/en.json, knowledge-capture-app/yarn.lock
Additional improvement:
- add breadcrumb
- fix language toggle
- add no results msg
=> :construction: KC App: add breadcrumb, fix language toggle, add no results msg

knowledge-capture-app/package.json, knowledge-capture-app/spec/Main.spec.js, knowledge-capture-app/spec/NoResults.spec.js, knowledge-capture-app/spec/SearchResults.spec.js, knowledge-capture-app/spec/app.spec.js, knowledge-capture-app/spec/mocks/mock.js, knowledge-capture-app/src/javascript/modules/LinkArticle.js, knowledge-capture-app/src/javascript/modules/Main.js, knowledge-capture-app/src/javascript/modules/NewArticle.js, knowledge-capture-app/src/javascript/modules/NoResults.js, knowledge-capture-app/src/javascript/modules/ResultBreadcrumb.js, knowledge-capture-app/src/javascript/modules/SearchFilters.js, knowledge-capture-app/src/javascript/modules/SearchInput.js, knowledge-capture-app/src/javascript/modules/SearchResults.js, knowledge-capture-app/src/javascript/modules/app.js, knowledge-capture-app/src/translations/en.json, knowledge-capture-app/yarn.lock
https://issues.liferay.com/browse/ISSUP-4244
=> :construction: KC App: be able to add new knowledge base articles, partial

knowledge-capture-app/spec/app.spec.js, knowledge-capture-app/spec/mocks/mock.js, knowledge-capture-app/src/javascript/lib/constants.js, knowledge-capture-app/src/javascript/modules/Main.js, knowledge-capture-app/src/javascript/modules/NewArticle.js, knowledge-capture-app/src/javascript/modules/app.js
- Correct the article template id for sandbox's Fast Track articles.
- Not changing locale to lower case causes Zendesk to redirect to a different path.
=> :construction: KC App Add Article bug fixes

knowledge-capture-app/src/javascript/lib/constants.js, knowledge-capture-app/src/javascript/modules/SearchResults.js, knowledge-capture-app/src/javascript/modules/app.js
https://issues.liferay.com/browse/ISSUP-4245 partial
=> :construction: KC App: clicking on a search result opens a modal

knowledge-capture-app/spec/Main.spec.js, knowledge-capture-app/spec/app.spec.js, knowledge-capture-app/spec/mocks/mock.js, knowledge-capture-app/src/javascript/lib/constants.js, knowledge-capture-app/src/javascript/modules/Modal.js, knowledge-capture-app/src/javascript/modules/SearchResults.js, knowledge-capture-app/src/javascript/modules/app.js
https://issues.liferay.com/browse/ISSUP-4245 partial
=> :construction: KC App: set up messaging between ticket sidebar and modal, display article body in modal

knowledge-capture-app/src/index.css, knowledge-capture-app/src/javascript/lib/utility.js, knowledge-capture-app/src/javascript/modules/LinkArticle.js, knowledge-capture-app/src/javascript/modules/Modal.js, knowledge-capture-app/src/javascript/modules/SearchResults.js, knowledge-capture-app/src/javascript/modules/app.js, knowledge-capture-app/src/translations/en.json
https://issues.liferay.com/browse/ISSUP-4245 partial
=> :construction: KC App: render basic modal content & add ability to link article in ticket editor from modal

knowledge-capture-app/src/javascript/modules/Main.js, knowledge-capture-app/src/javascript/modules/NoResults.js, knowledge-capture-app/src/javascript/modules/SearchInput.js, knowledge-capture-app/src/javascript/modules/SearchResults.js
https://issues.liferay.com/browse/ISSUP-4352
=> ISSUP-4352 style updates

knowledge-capture-app/spec/SearchFilter.spec.js, knowledge-capture-app/src/javascript/lib/constants.js, knowledge-capture-app/src/javascript/modules/Main.js, knowledge-capture-app/src/javascript/modules/SearchFilters.js
https://issues.liferay.com/browse/ISSUP-4406
=> :construction: KC APP: Perserve the language filter selection when user returns to main search interface from add article

theme/src/resources/templates/category_pages/liferay_dxp_7_4.hbs
=> Updated Links on Top Resources tab

theme/src/resources/templates/category_pages/liferay_dxp_7_2.hbs
=> Removed LCS card
